name: 'Terraform GitActions'

on:
  pull_request:
    branches:
    - main
  # push:
  #   branches:
  #   - main

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Google Authenticate
      uses: google-github-actions/auth@v0.4.0
      with:
        credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.1
      with:
        version: latest

  # Using gcloud cli
    # - name: Use gcloud CLI
    #   run: |
    #     gcloud config list

  # Optional step to obtain terraform binary
    # - name: Setup Terraform
    #   run: |
    #     sudo apt install wget curl unzip
    #     wget https://releases.hashicorp.com/terraform/0.14.7/terraform_0.14.7_linux_amd64.zip
    #     unzip terraform_0.14.7_linux_amd64.zip && chmod +x terraform

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.14.7

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: |
        terraform fmt -check

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      # if: github.ref == 'refs/heads/main' && github.event_name == 'pull_request'
      run: terraform apply -auto-approve

    - name: Terraform Destroy
      if: ${{ false }}
      run: terraform destroy -auto-approve
