name: 'Terraform gitactions'

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Google Authenticate
      uses: google-github-actions/auth@v0.4.0
      with:
        credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.1
      with:
        version: latest

    - name: Use gcloud CLI
      run: |
        gcloud config list

    - name: Setup Terraform
      run: |
        sudo apt install wget curl unzip
        wget https://releases.hashicorp.com/terraform/0.14.7/terraform_0.14.7_linux_amd64.zip
        unzip terraform_0.14.7_linux_amd64.zip && chmod +x terraform

    - name: Terraform Init
      run: ./terraform init

    - name: Terraform Format
      run: |
        ./terraform fmt -check || echo "terraform scrips not well formatted"

    - name: Terraform Plan
      run: ./terraform plan

    - name: Terraform Apply
      # if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: ./terraform apply -auto-approve
